# Generated by Django 4.2.7 on 2024-06-18 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
    ]
