# Generated by Django 4.2.7 on 2024-06-18 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0002_alter_customuser_options_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": ["CustomUser"],
                "verbose_name_plural": ["CustomUsers"],
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": ["Profile"], "verbose_name_plural": ["Profiles"]},
        ),
    ]
