# Generated by Django 4.2.7 on 2024-06-18 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0003_alter_customuser_options_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
    ]
